# Development profile: application-dev.properties
spring.application.name=hes-service-dev
nettyserver.port=29064
  #29065

hes.token.issuer=hes-admin
hes.token.access.validity=1800000
hes.token.refresh.validity=86400000
hes.token.secret=$2a$10$4Xz9f7p8Qz9kX3y2W5V2O.9J2kX8mY7nZ6W5V4U3I2O9P8Q7R6T5

# Logging
logging.level.com.memmcol=DEBUG
#logging.level.org.hibernate=DEBUG
logging.level.org.springframework=INFO

# Database
spring.datasource.url=jdbc:postgresql://172.16.10.60:8324/powerhub_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Memmc0L0405$}
spring.datasource.driver-class-name=org.postgresql.Driver

###Eureka is a Service Registry (from Netflix OSS, integrated with Spring Cloud).
eureka.client.service-url.defaultZone=http://172.16.10.60:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.autocommit=true
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Monthly billing determinants pipeline (continuous + 5-day grace window)
hes.billing.determinants.continuous.enabled=true
hes.billing.determinants.read-window-days=7
hes.billing.determinants.grace-period.days=5
hes.profile.execution.window.enabled=true

# HikariCP
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.pool-name=HikariPool-HES-DEV

# DevTools
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Spring Security (dev default)
spring.security.user.name=svc_hes_admin_dev
spring.security.user.password=devPassword123

#HES Executor pool
hes.meter.executor.size=10

# Actuator
management.endpoints.web.exposure.include=*
management.metrics.enable.cache=true
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted
