
#============================================================================
# Configure Main Scheduler Properties
#============================================================================
org.quartz.scheduler.instanceName=HES-Scheduler-DEV
org.quartz.scheduler.instanceId=AUTO

#============================================================================
# Configure ThreadPool
#============================================================================
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 5
org.quartz.threadPool.threadPriority = 5

#============================================================================
# Configure JobStore (PostgreSQL)
#============================================================================
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.useProperties=true
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.misfireThreshold=5000

#============================================================================
# Configure Cluster properties
#============================================================================
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.clusterCheckinInterval=1000

## Tell Quartz which DataSource to use
org.quartz.jobStore.dataSource=myDS

## Define the DataSource
#org.quartz.dataSource.myDS.driver=org.postgresql.Driver
org.quartz.dataSource.myDS.URL=jdbc:postgresql://172.16.10.60:8324/powerhub_db
org.quartz.dataSource.myDS.user=postgres
org.quartz.dataSource.myDS.password=Memmc0L0405$
org.quartz.dataSource.myDS.maxConnections=10

#org.quartz.dataSource.myDS.driver=org.postgresql.Driver
#org.quartz.dataSource.myDS.URL=jdbc:postgresql://localhost:5445/powerhub_db
#org.quartz.dataSource.myDS.user=postgres
#org.quartz.dataSource.myDS.password=P@ssw0rd#321
#org.quartz.dataSource.myDS.maxConnections=10

### DataSource provided by Spring via SchedulerFactoryBean.setDataSource()
### Spring maps its HikariCP pool to the name "myDS" below


