CREATE TABLE meters_connection_event (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         meter_no VARCHAR(12) NOT NULL UNIQUE,
                                         connection_type VARCHAR(100),
                                         connection_time TIMESTAMP,
                                         updated_at TIMESTAMP
);